name = "github-firehose"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "github-firehose.ainorthstar.tech"
custom_domain = true

[vars]
DASHBOARD_PIN = "4314"
# GITHUB_WEBHOOK_SECRET = "your-secret-here"

[[kv_namespaces]]
binding = "FIREHOSE_KV"
id = "b4114a58f5a44290ab4ff18e7477d001"

[[migrations]]
tag = "v2"
deleted_classes = ["FirehoseDO"]
